<?php

require_once dirname(__FILE__) . '/../../../modules/reports/reports.class.php';

/**
 * Test class for CReport.
 * Generated by PHPUnit on 2011-12-30 at 00:10:38.
 */
class CReportTest extends PHPUnit_Framework_TestCase {

    /**
     * @var CReport
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new CReport;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @todo Implement testGetFilename().
     */
    public function testGetFilename() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testHook_cron().
     */
    public function testHook_cron() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
