<?php

require_once dirname(__FILE__) . '/../../../../classes/w2p/Theme/TitleBlock.class.php';

/**
 * Test class for CTitleBlock.
 * Generated by PHPUnit on 2011-12-30 at 00:11:57.
 */
class CTitleBlockTest extends PHPUnit_Framework_TestCase {

    /**
     * @var CTitleBlock
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new CTitleBlock;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

}

?>
