<?php

require_once dirname(__FILE__) . '/../../../../classes/w2p/Theme/TitleBlock.class.php';

/**
 * Test class for w2p_Theme_TitleBlock.
 * Generated by PHPUnit on 2011-12-30 at 00:11:57.
 */
class w2p_Theme_TitleBlockTest extends PHPUnit_Framework_TestCase {

    /**
     * @var w2p_Theme_TitleBlock
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new w2p_Theme_TitleBlock;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @todo Implement testAddCell().
     */
    public function testAddCell() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testAddCrumb().
     */
    public function testAddCrumb() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testAddCrumbRight().
     */
    public function testAddCrumbRight() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testAddCrumbDelete().
     */
    public function testAddCrumbDelete() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testShow().
     */
    public function testShow() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testLoadExtraCrumbs().
     */
    public function testLoadExtraCrumbs() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testFindCrumbModule().
     */
    public function testFindCrumbModule() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
