<?php

require_once dirname(__FILE__) . '/../../../../classes/w2p/Theme/InfoTabBox.class.php';

/**
 * Test class for w2p_Theme_InfoTabBox.
 * Generated by PHPUnit on 2011-12-30 at 22:29:06.
 */
class w2p_Theme_InfoTabBoxTest extends PHPUnit_Framework_TestCase {

    /**
     * @var w2p_Theme_InfoTabBox
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new w2p_Theme_InfoTabBox;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @todo Implement testShow().
     */
    public function testShow() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
