<?php

require_once dirname(__FILE__) . '/../../../../classes/w2p/Utilities/HTTPRequest.class.php';

/**
 * Test class for w2p_Utilities_HTTPRequest.
 * Generated by PHPUnit on 2011-12-30 at 00:11:50.
 */
class w2p_Utilities_HTTPRequestTest extends PHPUnit_Framework_TestCase {

    /**
     * @var w2p_Utilities_HTTPRequest
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new w2p_Utilities_HTTPRequest;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @todo Implement testAddParameters().
     */
    public function testAddParameters() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testProcessRequest().
     */
    public function testProcessRequest() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
