<?php

require_once dirname(__FILE__) . '/../../../../classes/w2p/Controllers/Base.class.php';

/**
 * Test class for w2p_Controllers_Base.
 * Generated by PHPUnit on 2011-12-30 at 00:11:52.
 */
class w2p_Controllers_BaseTest extends PHPUnit_Framework_TestCase {

    /**
     * @var w2p_Controllers_Base
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new w2p_Controllers_Base;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @todo Implement testSetAccessDeniedPath().
     */
    public function testSetAccessDeniedPath() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testProcess().
     */
    public function testProcess() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
