<?php

require_once dirname(__FILE__) . '/../../../../classes/w2p/Authenticators/SQL.class.php';

/**
 * Test class for w2p_Authenticators_SQL.
 * Generated by PHPUnit on 2011-12-30 at 22:19:14.
 */
class w2p_Authenticators_SQLTest extends PHPUnit_Framework_TestCase {

    /**
     * @var w2p_Authenticators_SQL
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new w2p_Authenticators_SQL;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @todo Implement testAuthenticate().
     */
    public function testAuthenticate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testUserId().
     */
    public function testUserId() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
