<?php

require_once dirname(__FILE__) . '/../../../../classes/w2p/Authenticators/Base.class.php';

/**
 * Test class for w2p_Authenticators_Base.
 * Generated by PHPUnit on 2011-12-30 at 00:11:51.
 */
class w2p_Authenticators_BaseTest extends PHPUnit_Framework_TestCase {

    /**
     * @var w2p_Authenticators_Base
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new w2p_Authenticators_Base;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

}

?>
