<?php

require_once dirname(__FILE__) . '/../../../modules/system/system.class.php';

/**
 * Test class for CConfig.
 * Generated by PHPUnit on 2011-12-30 at 22:39:49.
 */
class CConfigTest extends PHPUnit_Framework_TestCase {

    /**
     * @var CConfig
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new CConfig;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

}

?>
