<?php

require_once dirname(__FILE__) . '/../../../modules/system/roles.class.php';

/**
 * Test class for CRole.
 * Generated by PHPUnit on 2011-12-30 at 22:38:58.
 */
class CRoleTest extends PHPUnit_Framework_TestCase {

    /**
     * @var CRole
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new CRole;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

}

?>
