<?php

require_once dirname(__FILE__) . '/../../../modules/system/sysvals.class.php';

/**
 * Test class for CSysVal.
 * Generated by PHPUnit on 2011-12-30 at 22:40:04.
 */
class CSysValTest extends PHPUnit_Framework_TestCase {

    /**
     * @var CSysVal
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new CSysVal;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

}

?>
