<?php

require_once dirname(__FILE__) . '/../../../modules/system/syskeys.class.php';

/**
 * Test class for CSysKey.
 * Generated by PHPUnit on 2011-12-30 at 22:39:12.
 */
class CSysKeyTest extends PHPUnit_Framework_TestCase {

    /**
     * @var CSysKey
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new CSysKey;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

}

?>
