<?php

require_once dirname(__FILE__) . '/../../../modules/system/budgets.class.php';

/**
 * Test class for CSystem_Budget.
 * Generated by PHPUnit on 2011-12-30 at 22:38:33.
 */
class CSystem_BudgetTest extends PHPUnit_Framework_TestCase {

    /**
     * @var CSystem_Budget
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new CSystem_Budget;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @todo Implement testGetBudgetAmounts().
     */
    public function testGetBudgetAmounts() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testStore().
     */
    public function testStore() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
