<?php

require_once dirname(__FILE__) . '/../../../../classes/w2p/Output/HTMLHelper.class.php';

/**
 * Test class for w2p_Output_HTMLHelper.
 * Generated by PHPUnit on 2011-12-30 at 00:11:52.
 */
class w2p_Output_HTMLHelperTest extends PHPUnit_Framework_TestCase {

    /**
     * @var w2p_Output_HTMLHelper
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new w2p_Output_HTMLHelper;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @todo Implement testRenderContactList().
     */
    public function testRenderContactList() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testCreateCell().
     */
    public function testCreateCell() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testCreateColumn().
     */
    public function testCreateColumn() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testRenderColumn().
     */
    public function testRenderColumn() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
