<?php

require_once dirname(__FILE__) . '/../../../../classes/w2p/Output/PageHandler.class.php';

/**
 * Test class for w2p_Output_PageHandler.
 * Generated by PHPUnit on 2011-12-30 at 00:11:52.
 */
class w2p_Output_PageHandlerTest extends PHPUnit_Framework_TestCase {

    /**
     * @var w2p_Output_PageHandler
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new w2p_Output_PageHandler;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @todo Implement testLoadExtras().
     */
    public function testLoadExtras() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
