<?php

require_once dirname(__FILE__) . '/../../../../classes/w2p/Core/Event.class.php';

/**
 * Test class for w2p_Core_Event.
 * Generated by PHPUnit on 2011-12-30 at 00:11:54.
 */
class w2p_Core_EventTest extends PHPUnit_Framework_TestCase {

    /**
     * @var w2p_Core_Event
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new w2p_Core_Event;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @todo Implement testGetResourceName().
     */
    public function testGetResourceName() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetEventName().
     */
    public function testGetEventName() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
