<?php

require_once dirname(__FILE__) . '/../../../../classes/w2p/Core/CustomFieldsParser.class.php';

/**
 * Test class for w2p_Core_CustomFieldsParser.
 * Generated by PHPUnit on 2011-12-30 at 00:11:56.
 */
class w2p_Core_CustomFieldsParserTest extends PHPUnit_Framework_TestCase {

    /**
     * @var w2p_Core_CustomFieldsParser
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new w2p_Core_CustomFieldsParser;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @todo Implement test_fetchFields().
     */
    public function test_fetchFields() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement test_fetchCustomRecordTypes().
     */
    public function test_fetchCustomRecordTypes() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement test_fetchPreviousData().
     */
    public function test_fetchPreviousData() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement test_getLabelHTML().
     */
    public function test_getLabelHTML() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testParseEditField().
     */
    public function testParseEditField() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testParseViewField().
     */
    public function testParseViewField() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testParseTableForm().
     */
    public function testParseTableForm() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement test_getVisibleKeysForType().
     */
    public function test_getVisibleKeysForType() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement test_parseShowFunction().
     */
    public function test_parseShowFunction() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testParseShowFunctions().
     */
    public function testParseShowFunctions() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testShowHideAllRowsFunction().
     */
    public function testShowHideAllRowsFunction() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
