<?php

require_once dirname(__FILE__) . '/../../../../classes/w2p/Core/CustomFieldSeparator.class.php';

/**
 * Test class for w2p_Core_CustomFieldSeparator.
 * Generated by PHPUnit on 2011-12-30 at 22:24:49.
 */
class w2p_Core_CustomFieldSeparatorTest extends PHPUnit_Framework_TestCase {

    /**
     * @var w2p_Core_CustomFieldSeparator
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new w2p_Core_CustomFieldSeparator;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @todo Implement testGetHTML().
     */
    public function testGetHTML() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
